export enum Role{
    USER,
    MEMBER,
    ADMIN
}

export enum Language {
    ENGLISH = 'en',
    SPANISH = 'es',
    FRENCH = 'fr',
    GERMAN = 'de',
    ITALIAN = 'it',
    PORTUGUESE = 'pt',
    RUSSIAN = 'ru',
    CHINESE = 'zh',
    JAPANESE = 'ja',
    KOREAN = 'ko',
    VIETNAMESE = 'vi',
    THAI = 'th',
    TURKISH = 'tr',
    ARABIC = 'ar',
    BULGARIAN = 'bg',
    CZECH = 'cs',
    DANISH = 'da',
    DUTCH = 'nl',
    GREEK = 'el',
    HUNGARIAN = 'hu',
    INDONESIAN = 'id',
    IRISH = 'ga',
    LATVIAN = 'lv',
    LITHUANIAN = 'lt',
    MALAY = 'ms',
    NORWEGIAN = 'no',
    POLISH = 'pl',
    ROMANIAN = 'ro',
    SLOVAK = 'sk',
    SLOVENIAN = 'sl',
    SWEDISH = 'sv',
    UKRAINIAN = 'uk',
    ARMENIAN = 'hy',
    BOSNIAN = 'bs',
    CROATIAN = 'hr',
  }
